# Generated by Django 4.0.5 on 2022-07-11 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_texst',
            new_name='question_text',
        ),
    ]
